const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_:OGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_:OGIN_SUCCESS',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    // fecth
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILD: 'FETCH_GENDER_FAILD',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILD: 'FETCH_POSITION_FAILD',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILD: 'FETCH_ROLE_FAILD',

    CREATE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    CREATE_USER_FAILD: 'SAVE_USER_FAILD',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILD: 'DELETE_USER_FAILD',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILD: 'EDIT_USER_FAILD',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILD: 'FETCH_ALL_USER_FAILD',

    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAILD: 'FETCH_TOP_DOCTOR_FAILD',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILD: 'FETCH_ALL_DOCTOR_FAILD',

    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILD: 'SAVE_DETAIL_DOCTOR_FAILD',

    FETCH_ALLCODE_TIME_SUCCESS: 'FETCH_ALLCODE_TIME_SUCCESS',
    FETCH_ALLCODE_TIME_FAILD: 'FETCH_ALLCODE_TIME_FAILD',
});
export default actionTypes;
